pipeline {
    agent any
    environment {
        dockerhub-credentials = credentials('dockerhub-login')
    }
    stages {
        stage('Pull Spring Calculator Image From Dockerhub') {
            steps {
                sh 'docker pull adriananogueira/calculator'
            }
        }
        stage('Run Spring Calculator') {
            steps {
                sh 'docker run --name calculator -dp 8090:8080 adriananogueira/calculator'
            }
        }
    }
}




