pipeline {
    agent any
    environment {
        registry = "adriananogueira/tema_01_final" // Seu nome de registro/repositório no Docker Hub
               registryCredential = 'dockerhub' // Nome da credencial de Docker Hub configurada no Jenkins
               dockerImage = "adriananogueira/tema_01_final:tagname" // Nome e tag da imagem Docker
           }
    stages {
        stage('Build and Push Docker Image') {
            steps {
                script {
                   withDockerRegistry([credentialsId: 'dockerhub', url: 'https://index.docker.io/v1/']) {

                       sh "echo 123Mudar@ | docker login -u adriana --password-stdin"
                   }
                }
                sh "docker build -t adriananogueira/tema_01_final:latest ."
                sh "docker pull adriananogueira/tema_01_final"
            }
        }

        stage('Run Docker Image') {
            steps {
                sh "docker run -d -p 8090:8090 adriananogueira/tema_01_final"
                sh "docker ps -a"
            }
        }
    }
}



