pipeline {
   agent any

   stages {
      stage('Download Image from Docker Hub') {
         steps {
            sh 'docker pull adriananogueira/calculadora:latest'
         }
      }

      stage('Run Docker Image') {
         steps {
            sh 'docker run -d -p 8090:8080 adriananogueira/calculadora:latest'
         }
      }
   }
}
