pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }

    stages {
        stage('Verificação do Código') {
            steps {
                checkout scm
            }
        }

        stage('Download de Artefato do JFrog Artifactory') {
            steps {
                script {
                    def rtServerId = "calculadora"
                    def rtDownloadSpec = """{
                        "files": [
                            {
                                "pattern": "tema-final-01/calculadora.war",
                                "target": "job-02/build/libs/calculadora.war"
                            }
                        ]
                    }"""
                    server = Artifactory.server rtServerId
                    server.download spec: rtDownloadSpec
                }
            }
        }

        stage('Construir a Imagem Docker com o Packer') {
            steps {
                sh 'packer plugins install github.com/hashicorp/docker'
                sh 'packer build -var "dockerhub_username=adriananogueira" -var "dockerhub_password=123Mudar@" job-02/packer.json'
            }
        }

        stage('Enviar a Imagem Docker para o Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                    sh "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD"
                    sh "docker push adriananogueira/tema_01_final:latest"
                }
            }
        }
    }
}
}