---
- name: Install and provide a functional Apache Tomcat Server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install correct Java version - OpenJDK 11 Headless
      apt:
        name: openjdk-11-jre-headless
        state: present

    - name: Criar apache Tomcat
      -get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz
        dest: /opt/apache-tomcat-9.0.41.tar.gz
        mode: 0755
        owner: root
        group: root
        validate_certs: no
        force: yes





    - name: Copiar o arquivo de configuração
      copy:
        src: /opt/tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: root
        group: root
        mode: 0755
        validate: /usr/sbin/tomcat9 -configtest
        notify: restart tomcat
