---
- name: Provision and Deploy Calculator App
  hosts: all
  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install OpenJDK 11
      become: yes
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Apache Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.0.12/bin/apache-tomcat-10.0.12.tar.gz"
        dest: "/tmp/apache-tomcat-10.0.12.tar.gz"

    - name: Extract Apache Tomcat
      become: yes
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-10.0.12.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Deploy calculator-app.war
      copy:
        src: "calculator-app.war"
        dest: "/opt/apache-tomcat-10.0.12/webapps/calculator-app.war"

    - name: Start Apache Tomcat
      become: yes
      shell: "/opt/apache-tomcat-10.0.12/bin/catalina.sh run"

  handlers:
    - name: Restart Tomcat
      become: yes
      shell: "/opt/apache-tomcat-10.0.12/bin/catalina.sh restart"
